### ISSUE TITLE
metaparse config disables constexpr c_str on apple llvm/clang

### ISSUE THREAD

**Issue by reuk** [sabel83/mpllibs#7]
If I wrap the GNUC check like follows to disable it, constexpr strings work fine. Maybe there's a different check that can be used instead?

```
#ifdef RECENT_CLANG_CAN_DO_THIS_ACTUALLY
#if defined __GNUC__ && (__GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ < 7))
#  define MPLLIBS_NO_CONSTEXPR_C_STR
#endif
#endif
```

**Comment by sabel83** [comment]
That check (and some other parts of the config header) should be removed and Boost.Config should be used instead. Thank you for pointing it out, I'll fix it.

**Comment by sabel83** [comment]
I've updated `config.hpp` on the develop branch of the boostorg/metaparse repo. Please take a look at it: https://github.com/boostorg/metaparse/tree/develop
